services:
  mysql: 
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    
  app:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_URI=${DB_URI}
      - ROOT_ID=${ROOT_ID}
    depends_on:
      - mysql
    volumes:
      - app_logs:/app/logs

volumes:
  mysql_data:
  app_logs:
