"""upd_contraints

Revision ID: 5fd52cd0a556
Revises: 2180a137aa7f
Create Date: 2025-02-04 08:33:38.414512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5fd52cd0a556'
down_revision: Union[str, None] = '2180a137aa7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=55),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=55),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=55),
               nullable=True)
    op.alter_column('users', 'language_code',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language_code',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=55),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=55),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=55),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
